import jsPDF from "jspdf";
import type { Itinerary } from "@shared/schema";

export function generateItineraryPDF(itinerary: Itinerary) {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - 2 * margin;
  let yPosition = margin;

  const addText = (text: string, fontSize: number, isBold: boolean = false, color: [number, number, number] = [0, 0, 0]) => {
    pdf.setFontSize(fontSize);
    pdf.setFont("helvetica", isBold ? "bold" : "normal");
    pdf.setTextColor(color[0], color[1], color[2]);
    
    const lines = pdf.splitTextToSize(text, contentWidth);
    
    if (yPosition + (lines.length * fontSize * 0.4) > pageHeight - margin) {
      pdf.addPage();
      yPosition = margin;
    }
    
    pdf.text(lines, margin, yPosition);
    yPosition += lines.length * fontSize * 0.4 + 5;
  };

  const addSpace = (space: number) => {
    yPosition += space;
  };

  pdf.setFontSize(24);
  pdf.setFont("helvetica", "bold");
  pdf.setTextColor(25, 25, 112);
  pdf.text(itinerary.title, pageWidth / 2, yPosition, { align: "center" });
  yPosition += 15;

  pdf.setFontSize(10);
  pdf.setFont("helvetica", "normal");
  pdf.setTextColor(100, 100, 100);
  pdf.text(`${itinerary.destination} • ${itinerary.duration} • ${itinerary.budget} Budget • ${itinerary.travelType}`, 
    pageWidth / 2, yPosition, { align: "center" });
  yPosition += 15;

  if (itinerary.highlights && itinerary.highlights.length > 0) {
    addText("Trip Highlights", 14, true, [25, 25, 112]);
    itinerary.highlights.forEach(highlight => {
      addText(`• ${highlight}`, 10, false, [60, 60, 60]);
    });
    addSpace(10);
  }

  itinerary.days.forEach((day) => {
    if (yPosition > pageHeight - 60) {
      pdf.addPage();
      yPosition = margin;
    }

    pdf.setFillColor(240, 248, 255);
    pdf.rect(margin, yPosition - 5, contentWidth, 15, "F");
    
    addText(`Day ${day.day}: ${day.title}`, 14, true, [25, 25, 112]);
    addSpace(5);

    day.activities.forEach((activity) => {
      const iconMap: Record<string, string> = {
        activity: "📍",
        meal: "🍽️",
        rest: "🛌"
      };
      
      addText(`${activity.time} ${iconMap[activity.type] || "•"} ${activity.title}`, 11, true, [0, 0, 0]);
      addText(activity.description, 9, false, [60, 60, 60]);
      addSpace(3);
    });

    addSpace(10);
  });

  pdf.setFontSize(8);
  pdf.setTextColor(150, 150, 150);
  pdf.text(
    `Generated by TripCraft AI • ${new Date().toLocaleDateString()}`,
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );

  pdf.save(`${itinerary.destination.replace(/\s+/g, "-")}-itinerary.pdf`);
}
